export default {
  CHANGE: "CHANGE",

  USER_CHANGE: "USER_CHANGE",
  POSTS_CHANGE: "POSTS_CHANGE",
  ADD_POST_CHANGE: "ADD_POST_CHANGE",
  CHAT_WITH_CHANGE: "CHAT_WITH_CHANGE",
  TIMELINE_CHANGE: "TIMELINE_CHANGE",

  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",

  RECIEVE_USER: "RECIEVE_USER",
  USER_LOGOUT: "USER_LOGOUT",
  RECIEVE_POSTS: "RECIEVE_POSTS",
  RECIEVE_CHAT_WITH: "RECIEVE_CHAT_WITH",

  ADD_NEW_DRAFT: "ADD_NEW_DRAFT",
  DELETE_DRAFT: "DELETE_DRAFT",
  PUBLISH_DRAFT: "PUBLISH DRAFT",
  EDIT_POST: "EDIT_POST",
  RESET_POST: "RESET_POST",

  RECIEVE_TIMELINE: "RECIEVE_TIMELINE"
};
